spring:
  datasource:
    username: root
    password: Wy568279.
    url: jdbc:mysql://localhost:3306/order?characterEncoding=utf-8&useSSL=false
    hikari:
      auto-commit: false
      maximum-pool-size: 100
      idle-timeout: 60000
      max-lifetime: 25200000
      minimum-idle: 20
      connection-timeout: 10000
      pool-name: read-write01
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
readwrite:
  scan: com.readwrite.service..*
  datasource:
    loadBalance: random
    master:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3316/order?characterEncoding=utf-8&useSSL=false
      isAutoCommit: false
      maxPoolSize: 100
      idleTimeout: 60000
      maxLifetime: 25200000
      minIdle: 20
      connectionTimeout: 10000
      poolName: read-write-master
    slave:
      - {username: root,
         password: 123456,
         url: "jdbc:mysql://localhost:3326/order?characterEncoding=utf-8&useSSL=false",
         isAutoCommit: false,
         maxPoolSize: 100,
         idleTimeout: 60000,
         maxLifetime: 25200000,
         minIdle: 20,
         connectionTimeout: 10000,
         poolName: read-write-slave1
      }
      - {username: root,
         password: 123456,
         url: "jdbc:mysql://localhost:3336/order?characterEncoding=utf-8&useSSL=false",
         isAutoCommit: false,
         maxPoolSize: 100,
         idleTimeout: 60000,
         maxLifetime: 25200000,
         minIdle: 20,
         connectionTimeout: 10000,
         poolName: read-write-slave2
      }

