spring:
  shardingsphere:
    props:
      sql-show: true
      # 使用narayana  XA实现
    #      xa-transaction-manager-type: Narayana
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/order0?characterEncoding=utf-8&useSSL=false
        username: root
        password: Wy568279.
        maximum-pool-size: 100
        idle-timeout: 60000
        max-lifetime: 25200000
        minimum-idle: 20
        connection-timeout: 10000
        pool-name: order0-pool
        connection-test-query: select 1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3316/order1?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maximum-pool-size: 100
        idle-timeout: 60000
        max-lifetime: 25200000
        minimum-idle: 20
        connection-timeout: 10000
        pool-name: order1-pool
        connection-test-query: select 1
    rules:
      sharding:
        sharding-algorithms:
          #注:   shardingsphere-jdbc配置分片算法名时,由于shardingsphere-jdbc对于spring boot V2.0+的属性使用Binder解析,所以算法名不能存在 _
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{buyer_member_id % 2}
          table-inline:
            type: INLINE
            props:
              algorithm-expression: order$->{order_id % 16 +1}

        binding-tables:
          - t_order
        tables:
          t_order:
            ## 行表达式标识符可以使用 ${...} 或 $->{...}，但前者与 Spring 本身的属性文件占位符冲突，因此在 Spring 环境中使用行表达式标识符建议使用 $->{...}。
            actual-data-nodes: ds$->{0..1}.order$->{1..16}
            database-strategy:
              standard:
                sharding-column: buyer_member_id
                sharding-algorithm-name: database-inline
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: table-inline



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
