server:
  port: 8081
  
rpc:
  props:
    consumer:
      loadBalance: random
      proxy: jdk
#      client: netty
      registry:
        registryAddress: 127.0.0.1:2181
        registry: zookeeper



